testKey: 111
serverAddr: 101.42.242.201:2181
server:
  port: 8085
workers:
  - 111
  - 222
  - 333

tag-config:
  reqTags:
    - uid
    - ip
  logTags:
    - errno
    - node
  regex: ""
  delimiter: "|"
  join: =

