serverAddr: 127.0.0.1:2379
jlog:
  center-config:
    center: etcd
    etcdServer: ${etcdServer:http://127.0.0.1:2379} #etcd的地址，重要！！！
    nacosServer: 101.42.242.201:8848
    zkServer: 101.42.242.201:2181


server:
  port: 8081
